# File: azure-pipelines.yml

# Build Name / Format
name: PowerAppsTestAutomation-$(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
    - repository: PowerAppsTestAutomation
      type: github
      # GitHub Repo (e.g. <FORK>/PowerAppsTestAutomation)
      name: microsoft/PowerAppsTestAutomation
      ref: master
      # Name of the GitHub OAuth ADO Service Connection
      endpoint: <ADO GitHub OAuth Service Connection Name>

parameters:
 - name: image
   displayName: Pool Image
   type: string
   # See https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md#use-a-microsoft-hosted-agent for more pool types
   default: windows-latest
   values:
   - windows-latest
   - vs2017-win2016
   - windows-2019
 - name: BrowserType
   displayName: Browser Type
   type: string
   default: All
   values:
   - Chrome
   - Firefox
   - All
 - name: OnlineUsername
   displayName: Online Username
   type: string
 - name: OnlinePassword
   displayName: Online Password
   type: string
   secret: true

jobs:
- job: "PowerAppsTestFrameworkAutomation"
  pool:
    name: ${{ parameters.image }}
    demands:
    - msbuild
    - visualstudio
    - vstest
  variables:
  - name: BrowserFirefox
    value: Firefox
  - name: BrowserChrome
    value: Chrome
  - name: PortalUrl
    value: https://make.powerapps.com
    # FileName where TestAutomationURLs are stored in JSON format
  - name: TestUrlFileName 
    value: TestAutomationURLs.json
    # Browser PrivateMode usage (true/false)
  - name: PrivateMode
    value: true
    # Project name of repo containing TestAutomationURLs (spaces encoded as %20)
  - name: LocalProjectName
    value: Contoso%20Test%20Framework

  steps:
  - checkout: self
  - checkout: PowerAppsTestAutomation
  #- template: localsteps.yml # Provide optional local YAML template here
  - template: frameworksteps.yml@PowerAppsTestAutomation
    parameters:
      OnlineUsername: $(OnlineUsername)
      OnlinePassword: $(OnlinePassword)
      BrowserTypeChrome: $(BrowserChrome)
      BrowserTypeFirefox: $(BrowserFirefox)
      OnlineUrl: $(PortalUrl)
      # File location format is /s/TeamProjectName/FilePathToTestAutomationURLs.json
      TestAutomationURLFilePath: $(Build.SourcesDirectory)\$(System.TeamProject)\Samples\$(TestUrlFileName)
      UsePrivateMode: $(PrivateMode)